server:
  port: 8083
spring:
  application:
    name: book-server

  zipkin:
    kafka:
      topic: zipkin
  sleuth:
    sampler:
      percentage: 1.0
  kafka:
    bootstrap-servers: 10.33.80.101:9092
    consumer:
      group-id: ${spring.application.name}
      auto-offset-reset: latest
      enable-auto-commit: true
      auto-commit-interval: 1000

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/user_system?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456

  redis:
    host: 10.33.80.101

  cloud:
    inetutils:
      preferred-networks[0]: 10

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

ribbon:
  ServerListRefreshInterval: 2000


reliable:
  message:
    producerGroup: book-server
    reliableMessageConsumer: true
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml