server:
  port: 8083
spring:
  application:
    name: book-server

  zipkin:
    kafka:
      topic: zipkin
  sleuth:
    sampler:
      percentage: 1.0
  kafka:
    bootstrap-servers: 10.33.80.101:9092

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
#      defaultZone: http://10.33.80.101:7010/eureka/,http://10.33.80.101:7011/eureka/


#security:
#  oauth2:
#    resource:
#      id: account-service
#      user-info-uri: http://localhost:8001/user
#      prefer-token-info: false



