logging:
  config: classpath:logback.xml
server:
  port: 7000
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        default-application-name: config-server
        git:
          uri: http://10.33.80.121/lilei/config.git
          username: config-server
          password: 12345678
          search-paths: '{application}'
          force-pull: true


management:
  security:
    enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    hostname: 10.33.50.40
    lease-renewal-interval-in-seconds: 5 #服务刷新时间配置，每隔这个时间会主动心跳一次
    lease-expiration-duration-in-seconds: 15 #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除,#注意，EurekaServer一定要设置eureka.server.eviction-interval-timer-in-ms否则这个配置无效，这个配置一般为服务刷新时间配置的三倍
