server:
  port: 7030
spring:
  application:
    name: gataway-server

  profiles:
    active: @profile-active@

zuul:
  ribbon:
    eager-load:
      enabled: true
      clients: auth-server,user-server
  ignoredServices: '*'

management:
  security:
    enabled: false




