server:
  port: 8761
spring:
  application:
    name: eureka-server
security:
  basic:
    enabled: false
eureka:
  client:
    register-with-eureka: false   #是否将eureka自身作为应用注册到eureka注册中心
    fetch-registry: false #为true时，可以启动，但报异常：Cannot execute request on any known server


#eureka:
#  instance:
#    hostname: localhost
#  client:
#    serviceUrl:
#      defaultZone: ${ADDITIONAL_EUREKA_SERVER_LIST}


docker-compose
#eureka:
#  image: reg.zhongjiaxin.com/system/eureka-server:latest
#  container_name: eureka
#  restart: always
#  ports:
#    - "8761:8761"
#  environment:
#    - ADDITIONAL_EUREKA_SERVER_LIST=http://10.33.80.101:8761/eureka/,http://10.33.80.114:8761/eureka/
#    - EUREKA_INSTANCE_HOSTNAME=10.33.80.101
#  volumes:
#    - /etc/localtime:/etc/localtime:ro
