server:
  port: 8001
spring:
  application:
    name: auth-server
  redis:
    host: 127.0.0.1
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/


security:
  oauth2:
    resource:
      filter-order: 3  # 待确认

oauth:
  client:
    jwtSigningKey: jwtSigningKey
    clients[0]:
      clientId: user
      clientSecret: userSecret
      accessTokenValidateSeconds: 7200
      scope: "*"
    clients[1]:
      clientId: book
      clientSecret: bookSecret
      accessTokenValidateSeconds: 7200
      scope: "*"



#检查token
#http://localhost:8888/oauth/check_token?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvcmdhbml6YXRpb25JZCI6ImxpbGVpOiIsInVzZXJfbmFtZSI6ImxpbGVpIiwic2NvcGUiOlsid2ViY2xpZW50Il0sImV4cCI6MTUzMTE1MDQ5NiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9BRE1JTiJdLCJqdGkiOiJiMzlmZGVjMy1hZDdhLTRlYTUtOWYwOC02NDFmNjg0NWQ0YWIiLCJjbGllbnRfaWQiOiJhZG1pbiJ9.GybC5EQJVgwGioWAk8LibXaW4mgpIDkpFBfEwNIB3uU