server:
  port: 8082
spring:
  application:
    name: user-server
  zipkin:
    kafka:
      topic: zipkin

  kafka:
    bootstrap-servers: 10.33.80.101:9092

  sleuth:
    sampler:
      percentage: 1.0


  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.33.80.101:3306/user_system?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456


mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/


reliable:
  message:
    producerGroup: user-server

