server:
  port: 8082
spring:
    application:
      name: user-server

eureka:
  client:
    service-url:
      defaultZone: http://root:root@127.0.0.1:8761/eureka/




#cloud:
#  oauth2:
#    client:
#      id: user-server
#      accessTokenUrl: http://localhost:8888/oauth/token
#      clientId: admin
#      clientSecret: admin
#      clientAuthenticationScheme: header
#      tokenStore: jwt



