server:
  port: 8082
spring:
  application:
    name: user-server
  zipkin:
    kafka:
      topic: zipkin

  kafka:
    bootstrap-servers: 10.33.80.101:9092

  sleuth:
    sampler:
      percentage: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/




