server:
  port: 8082
spring:
    application:
      name: user-server

eureka:
  client:
    service-url:
      defaultZone: http://root:root@127.0.0.1:8761/eureka/


security:
  oauth2:
    resource:
      id: account-service
      user-info-uri: http://localhost:8000/auth
      prefer-token-info: false



